# Numpy
NumPy is the fundamental package for scientific computing with Python. It gives support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## Resources
* [Quickstart tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* [User Guide](https://docs.scipy.org/doc/numpy/user/)
* [Reference Guide](https://docs.scipy.org/doc/numpy/reference/)


In [1]:
# Import numpy.
# As it will be widely used, better to give it a nickname, or an alias. Traditionnaly, it's "np":
import numpy as np

# Create an array

In [2]:
a1=np.array([1,2,3,6,4])
print ("a1:",a1)

# or you can create from a list (or a tuple)
l=[1.3,2.9,5.4]
a2=np.array(l)
print ("a2:",a2)

# multidimensional arrays
# you can created them from a list of lists

a3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print (a3)

a1: [1 2 3 6 4]
a2: [ 1.3  2.9  5.4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Some important attributes of an array:
* **ndarray.ndim**:
    the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

* **ndarray.shape**:
    the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

* **ndarray.size**:
    the total number of elements of the array. This is equal to the product of the elements of shape.

* **ndarray.dtype**:
    an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [3]:
for a in [a1,a2,a3]:
    print ("NDIM: ",a.ndim)
    print ("SHAPE:",a.shape)
    print ("SIZE: ",a.size)
    print ("DTYPE:",a.dtype)
    print ("")

NDIM:  1
SHAPE: (5,)
SIZE:  5
DTYPE: int64

NDIM:  1
SHAPE: (3,)
SIZE:  3
DTYPE: float64

NDIM:  2
SHAPE: (3, 3)
SIZE:  9
DTYPE: int64



The elements of a numpy array are all of the *same type*
If you create an aray using elements with different type, Python tries to convert them
If this is not possible, an error is 

In [4]:
a1=np.array([1,2,4.2])
print (a1)
print (a1.dtype)

[ 1.   2.   4.2]
float64


In [5]:
a2=np.array([1,2,"D"])
print (a2)
a=a2.dtype
print(a2.dtype)

['1' '2' 'D']
<U21


Once the type of an array is defined, one can insert values of type that can be transformed to the type of the array

In [6]:
a3=np.array([1,2,4.2])
a3[0]=3 # 3 will be converted to 3.0 (float)

# a1[0]="A" # will raise an ERROR, "A" can not converted to a float!
a3


array([ 3. ,  2. ,  4.2])

[Data type objects reference manual](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html). This doc contains some **ADVANCED TOPICS**. You can skip this doc


## array-generating functions

There many functions in numpy that generate arrays of different forms. Some of the more common are:

### arange
Return evenly spaced values within a given interval.

In [7]:
x1=np.arange(10)     # 10 is not included!!
x2=np.arange(3,10)
x3=np.arange(3,10,2)

print (x1)
print (x2)
print (x3)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[3 5 7 9]


### linspace and logspace 
Use the help system -`?` or `help()` or `Shift+TAB`- to learn about these functions!

In [8]:
x1=np.linspace(2,4,5) # 5 evenly spaced points between 2 and 5
x2=np.logspace(2,4,5) # points are logarithmically spaced. start and end points are 10**2 and 10**4

print (x1)
print (x2)


[ 2.   2.5  3.   3.5  4. ]
[   100.            316.22776602   1000.           3162.27766017  10000.        ]


### meshgrid
Return coordinate matrices from coordinate vectors.

In [9]:
x,y=np.meshgrid([1,2,3],[5,6,9])
print (x)
print('------------------------------------')
print (y)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
------------------------------------
[[5 5 5]
 [6 6 6]
 [9 9 9]]


### mgrid
create 2 2D arrays (coordinates matrices), one describing how x varies, the other for y.

In [10]:
# 
y, x = np.mgrid[0:5, 0:3] # This is not a function!!! notice the []
print(x)
print('------------------------------------')
print(y)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
------------------------------------
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


### diag

In [11]:
# a diagonal matrix
np.diag([1,4,3])

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 3]])

In [12]:
# diagonal with offset from the main diagonal
np.diag([1,4,3], k=1)


array([[0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### zeros and ones
`np.zeros(shape,dtype=float)` return a new array of given shape and type, filled with zeros. The default output is a float array

`np.ones` return an array filled with ones

In [13]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [14]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [15]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### random data
[https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html)

In [16]:
from numpy import random

In [17]:
# uniform random numbers in [0,1]
random.rand(2,3) # 

array([[ 0.19082265,  0.37419395,  0.15391962],
       [ 0.50381642,  0.10610046,  0.83368818]])

In [18]:
# standard normal distributed random numbers
random.randn(3,2)

array([[ 1.20555582,  0.63508512],
       [ 0.05184807,  0.39801873],
       [ 1.37586016, -0.4591719 ]])

In [19]:
# uniform numbers in a range
random.uniform(3,5,(3,2))

array([[ 4.03563964,  3.86032431],
       [ 3.60816382,  4.88981753],
       [ 3.84222313,  4.27393881]])

In [20]:
# normal distruted with given mean value and std
random.normal(loc=3,scale=.1,size=9)

array([ 2.92908704,  2.96422911,  2.89186426,  2.94296937,  2.81557114,
        3.0513568 ,  3.06285816,  2.85192943,  2.893159  ])

`choice(a[, size, replace, p])`
Generates a random sample from a given 1-D array.
For more info, read the doc!


In [21]:
a=np.array([1,3,4,6,9,12])
print (a)
random.choice(a,3,replace=False) #replace=False for a sample without repetitions

[ 1  3  4  6  9 12]


array([9, 1, 3])

# Operations

## Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.


In [22]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [23]:
v2=v1+2
v3=v1*2
print (v2)
print (v3)


[2 3 4 5 6]
[0 2 4 6 8]


## Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is *element-wise* operations:


In [24]:
v1=np.array([1,2,5,2])
v2=np.array([5,1,0,3])
print (v1)
print (v2)
print ("SUM")
print (v1+v2)
print ("MULT")
print (v1*v2)


[1 2 5 2]
[5 1 0 3]
SUM
[6 3 5 5]
MULT
[5 2 0 6]


## boolean operations`

### `&` : logical and

In [25]:
a=np.arange(0,5,.5)
cond1= a>2
cond2=a<4
cond=cond1&cond2

print (a)
print (cond1)
print (cond2)
print (cond)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5]
[False False False False False  True  True  True  True  True]
[ True  True  True  True  True  True  True  True False False]
[False False False False False  True  True  True False False]


### `|` : logical or

In [26]:
cond1= a<2
cond2=a>4
cond=cond1 | cond2
print (cond1)
print (cond2)
print (cond)

[ True  True  True  True False False False False False False]
[False False False False False False False False False  True]
[ True  True  True  True False False False False False  True]


### ~: not

In [27]:
cond2=~cond1
print (cond1)
print (cond2)

[ True  True  True  True False False False False False False]
[False False False False  True  True  True  True  True  True]


## Mathematical functions
[https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)

In [28]:
a=np.arange(0,4)
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692])

In [29]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001])

### nans, inf
There are special values defined in numpy: nan, inf

In [30]:
np.log10(a)

/home/marco/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.30103   ,  0.47712125])

In [31]:
b=1/a
print (b)

[        inf  1.          0.5         0.33333333]


/home/marco/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [32]:
np.isfinite(b)

array([False,  True,  True,  True], dtype=bool)

In [33]:
a=np.array([-3,2,10])
np.sqrt(a) # the square root of a negative number is Not A Number

/home/marco/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([        nan,  1.41421356,  3.16227766])

In [34]:
np.isfinite(a) # note!! nan is finite!

array([ True,  True,  True], dtype=bool)

`nan` (Not A Number) can used as a poor-man's mask. When you make an operation on an array with a `nan`, the result will be
an array with a `nan`.

In [35]:
a=np.arange(2,5,.5)
a[3]=np.nan
a

array([ 2. ,  2.5,  3. ,  nan,  4. ,  4.5])

In [36]:
a+3

array([ 5. ,  5.5,  6. ,  nan,  7. ,  7.5])

In [37]:
np.sqrt(a)

array([ 1.41421356,  1.58113883,  1.73205081,         nan,  2.        ,
        2.12132034])

## Other useful functions

### min and max

In [38]:
a=np.random.rand(5)
print (a)
print (np.amin(a))
print (np.amax(a))

[ 0.12089713  0.3564862   0.01969188  0.40464498  0.5888934 ]
0.0196918758862
0.588893400187


you can calculate the min (and max) along each axis:

In [39]:
a=np.random.rand(3,2)
print (a)
min_0=np.amin(a,axis=0)
min_1=np.amin(a,axis=1)
print ("MIN axis=0")
print (min_0)
print ("MIN axis=1")
print (min_1)

[[ 0.78492726  0.08317924]
 [ 0.02177006  0.53553599]
 [ 0.17201807  0.77495851]]
MIN axis=0
[ 0.02177006  0.08317924]
MIN axis=1
[ 0.08317924  0.02177006  0.17201807]


`min()` and `max()` are equivalent to `amin()` and `amax()`

In [40]:
print (np.min(a,axis=0))
print (np.amin(a,axis=0))


[ 0.02177006  0.08317924]
[ 0.02177006  0.08317924]


### argmin, argmax
Returns the indices of the minimum and maximum values along an axis.

In [41]:
a=np.random.rand(5)
idx=a.argmin()
print (a)
print (idx)


[ 0.48832813  0.8835625   0.49967223  0.58442227  0.73950143]
0


### sum

In [42]:
print (a)
print ("---")
print (np.sum(a))
print ("---")
print (a.sum(axis=0))


[ 0.48832813  0.8835625   0.49967223  0.58442227  0.73950143]
---
3.19548655344
---
3.19548655344


### mean and standard deviation

In [43]:
# create an array of 100 elements
# from a normal (Gaussian) distribution with mean=5 and standard deviation=0.2 
x=np.random.normal(5,.2,100)

# calculate the mean and std
mean=np.mean(x)
median=np.median(x)
std=np.std(x)
print ("Mean  :",mean)
print ("Median:",median)
print ("std   :",std)

Mean  : 4.98215349468
Median: 4.96645450972
std   : 0.190288809041


# Numpy: functions and methods

So far we have used numpy functions, like `np.mean(array)`.
The same results can be obtained also using *methods*.

A *method* is a function that is associated with a particular *class*.
Each object that are member of the class `numpy.array` has a number of functions associated to it.
When you write
```python
np.mean(x)
```
you are using the numpy function `mean`, and you pass `x` as an argument.
The same can be obtained with
```python
x.mean()
```
You are using the *method* `mean` of the class numpy.array (`x` is a numpy array).

In [44]:
x=np.random.uniform(3,5,100)
m1=np.mean(x)
m2=x.mean()
print (m1)
print (m2)


3.96535541284
3.96535541284


In [45]:
print (x.min())
print (np.amin(x,axis=0))

3.00067082678
3.00067082678


# Manipulating arrays

## Indexing

We can index elements in an array using square brackets and indices:


In [46]:
# v is a 1D vector
# M is a matrix (2D vector)
v=np.array([4,3,8,11])
m=np.array([[3,4,11],[7,5,4]])

print (v)
print (v.shape)
print("-----")
print (m)
print (m.shape)

[ 4  3  8 11]
(4,)
-----
[[ 3  4 11]
 [ 7  5  4]]
(2, 3)


In [47]:
# v is a vector, and has only one dimension, taking one index
v[0]

4

In [48]:
# M is a matrix, or a 2 dimensional array, taking two indices 
m[1,1]

5

In [49]:
m[1,:] # row 1

array([7, 5, 4])

In [50]:
m[:,1] # column 1

array([4, 5])

We can assign new values to elements in an array using indexing:

In [51]:
m[0,0]=9
m

array([[ 9,  4, 11],
       [ 7,  5,  4]])

In [52]:
# also works for rows and columns
m[1,:] = 0
m[:,2] = -1
m

array([[ 9,  4, -1],
       [ 0,  0, -1]])

## Index slicing

Index slicing is the technical name for the syntax M[lower:upper:step] to extract part of an array:


In [53]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [54]:
a[1:3]

array([2, 3])

Array slices are mutable: if they are assigned a new value the original array from which the slice was extracted is modified:


In [55]:
a[1:3] = [-2,-3]
a

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in M[lower:upper:step]:

In [56]:
a[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [57]:
a[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [58]:
a[:3] # first three elements

array([ 1, -2, -3])

In [59]:
a[3:] # elements from index 3


array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [60]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [61]:
a[-1] # the last element in the array


5

In [62]:
a[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:


In [63]:
a = np.array([[n+m*10 for n in range(5)] for m in range(5)])

a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [64]:
# a block from the original array
a[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [65]:
a[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

## Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index:


In [66]:
row_indices = [1, 2, 3]
a[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [67]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
a[row_indices, col_indices]


array([11, 22, 34])

We can also use index masks: If the index mask is an Numpy array of data type bool, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element:


In [68]:
v = np.array([n for n in range(5)])
v

array([0, 1, 2, 3, 4])

In [69]:
row_mask = np.array([True, False, True, False, False])
v[row_mask]

array([0, 2])

In [70]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
v[row_mask]

array([0, 2])



This feature is very useful to conditionally select elements from an array, using for example comparison operators:


In [71]:
x = np.arange(0, 10, 0.5)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [72]:
mask = (5 < x) & (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False], dtype=bool)

In [73]:
x[mask]

array([ 5.5,  6. ,  6.5,  7. ])

### where
The index mask can be converted to position index using the where function

In [74]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [75]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

array([ 5.5,  6. ,  6.5,  7. ])

###  <span style="color:red">EXERCISE:</span> : percentile

Define an array with 1000 random numners uniformely distributed between 3 and 7.
Find a way to calculate the 80-th percentile of the sample 

*Hint*: Google helps!! but also the section of the routine list in the numpy reference guide https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.html

For example, the 80th percentile is the value (or score) below which 80% of the data may be found.
Verify that this is the case for the array you defined.

In [76]:
## your solution



uncomment the first line on the following cell and run the cell to see the solution

In [77]:
# %load solutions/percentile.py

# Reshaping, resizing and stacking arrays
The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [78]:
a = np.array([[n+m*10 for n in range(4)] for m in range(3)])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [79]:
n, m = a.shape
print (n,m)

3 4


In [80]:
b= a.reshape((1,n*m))
b

array([[ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23]])

 <span style="color:red">**NOTE**: **Arrays share memory** :</span>(remember? like lists!)

When you `reshape` you just create *a different view of the same data*

In [81]:
b[0,0:2] = 5 # modify the array

print (b)
print ("----")
print (a)


[[ 5  5  2  3 10 11 12 13 20 21 22 23]]
----
[[ 5  5  2  3]
 [10 11 12 13]
 [20 21 22 23]]


## `flatten()`
makes a higher-dimensional array into a vector. But this function *create a copy* of the data.

In [82]:
b=a.flatten()
b

array([ 5,  5,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23])

In [83]:
b[0:3]=9
print (b)
print ("----")
print (a)

[ 9  9  9  3 10 11 12 13 20 21 22 23]
----
[[ 5  5  2  3]
 [10 11 12 13]
 [20 21 22 23]]


if one of the axis length is left as -1. Numpy will compute this dimension for you.

In [84]:
a1 = np.arange(15).reshape((-1, 5))

print (a1.shape)
print ("---")
print (a1)

(3, 5)
---
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Transpose

In [85]:
a = np.array([[n+m*10 for n in range(4)] for m in range(3)])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [86]:
a.transpose()

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23]])

In [87]:
# same thing
a.T

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23]])

## Stacking and repeating arrays

Using the functions `repeat`, `tile`, `vstack`, `hstack`, and `concatenate` we can create larger vectors and matrices from smaller ones:

### tile and repeat


In [88]:
a = np.array([[1, 2],[3, 4]])
print (a)
# repeat each element 3 times
print ("no axis, repeat the flatten array")
print (np.repeat(a, 3))
print ("axis=0; repeat each row")
print (np.repeat(a,3,axis=0))
print ("axis=1, repeat each column")
print (np.repeat(a,3,axis=1))




[[1 2]
 [3 4]]
no axis, repeat the flatten array
[1 1 1 2 2 2 3 3 3 4 4 4]
axis=0; repeat each row
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
axis=1, repeat each column
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]


In [89]:
# tile the matrix 3 times 
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

### concatenate

In [90]:
b = np.array([[5, 6]])

In [91]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
c=b.reshape(2,1)
print (a.shape)
print (c.shape)

# if you want to concatenate along axis=1 (columns),
# then all arrays must have the same number of rows 
np.concatenate((a,c),axis=1)


(2, 2)
(2, 1)


array([[1, 2, 5],
       [3, 4, 6]])

### hstack and vstack
Take a sequence of arrays and stack them horizontally (`hstack`) or vertically (`vstack`) to make
a single array.

In [93]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
np.hstack((a,c))

array([[1, 2, 5],
       [3, 4, 6]])

# Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference).


In [95]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [96]:
# now b is referring to the same array data as a 
b = a
b[0,0]=9 # changing b affects a

print (b)
print ("---")
print (a)


[[9 2]
 [3 4]]
---
[[9 2]
 [3 4]]




If we want to avoid this behavior, so that when we get a new completely independent object `b` copied from `a`, then we need to do a so-called "deep copy" using the function `copy`:


In [97]:
a = np.array([[1, 2], [3, 4]])
b=a.copy()
b[0,0]=9

print (b)
print ("---")
print (a)

[[9 2]
 [3 4]]
---
[[1 2]
 [3 4]]


# Load  ascii files
`numpy` provides a useful functions to load data as numpy arrays from a text file, [`numpy.loadtxt`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.loadtxt.html)

The file `data/messier.txt` is the list of Messier objects, their equatorial (`RA,DEC`) and Galactic (`l,b`) coordinates. These are the first lines shown as an example:
```
# name          RA         DEC           l           b
  M1     83.633212  +22.014460  184.557556   -5.784277
  M2    323.362552   -0.823318   53.370790  -35.769774
  M3    205.546777  +28.375454   42.208085   78.708396
  M4    245.897511  -26.525522  350.973585   15.971828
```

Let's read the RA,DEC coordinates using `numpy.loadtxt`

In [98]:
import numpy as np
data=np.loadtxt("data/messier.txt",usecols=(1,2))
print (data.shape)
# or, if you want to unpack the data and create the arrays:
ra,dec,l,b=np.loadtxt("data/messier.txt",usecols=(1,2,3,4),unpack=True)
print (ra[:2])
print (dec[:2])
print (l[:2])
print (b[:2])


(110, 2)
[  83.633212  323.362552]
[ 22.01446   -0.823318]
[ 184.557556   53.37079 ]
[ -5.784277 -35.769774]


If you need to read columns that contain something different from `float`, you need to use the `dtype` keyword.
Its use is quite complicated, we will see how to read this kind of data much more easily using `astropy`.

# Numpy reference guide

`Numpy` is a complex packages with a huge number of sub-modules. In this notebook we found some of them.
You can find the `numpy` referece guide here: https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html

Here is a list of some of the sections that you may find useful:
* Array manipulation routines: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-manipulation.html
* Mathematical functions: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html
* Statistics: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html
* Random sampling: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html
* Polinomials: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.polynomials.html
